### ISSUE TITLE
Run commands On colsole / Custom Deaths Message with Gun Name

### ISSUE THREAD

**Issue by MillionaireHope** [InfinityGamers/Weapons#9] opened 2019-10-25 06:34 UTC
_Hello I am a server owner and I am using your plugin on one of my servers. I am here to ask you if you can allow this to have a custom death message for example_

**[Player] was shot and killed by [Killer] with [Gun]**

**also may you allow this plugin to be able to run commands via Console
I've tried doing it but it says (Please run command in-game)**

You can get in contact with me on twitter
[https://twitter.com/hopefleegolden](url)

**and or discord
MillionaireHope#2870**

thank you for making this plugin

**Comment by KadTheHunter** [comment] 2019-10-25 14:32
Your first question is a duplicate of #5 but you explain it in good detail, and your second question is a duplicate of #8. For the second issue (#8), exactly what do you mean by allowing the commands to be run via console? The commands in general are intended to be run by players in-game, as it adds items to them by default, if no other player(s) are specified. Do you mean editing it so the console can add Guns and Ammunition to players in-game?

*NOTE:* I am not the owner or author of this plugin, @xBeastMode is, but seeing as they haven't answered anything in a while, I'm volunteering to sort out some minor issues, and avoid duplicates being made, so as to allow @xBeastMode to actually handle the issues whenever he returns instead of wading through a few dozen duplicate or easily answered issues and questions.

**Comment by MillionaireHope** [comment] 2019-10-26 18:48
Do you have discord or twitter @LegoFan48737 if so message me I would  appreciate it if you can help my with the issues.


Discord.   MillionaireHope#2870
Twitter. @HopefleeGolden

**Comment by xBeastMode** [comment] 2020-12-31 19:47
This is an experimental plugin, it is not meant to be used in production servers. Most of my open source work is experiemental and I don't plan on updating it any longer.

**Closed as completed by xBeastMode** 2020-12-31 19:47 UTC
